from typing import Any, Sequence

class SingBoxError(RuntimeError): ...

class SingBox:
    def __init__(self) -> None: ...
    def startFromJSON(self, json: str) -> None: ...
    def stop(self) -> None: ...
    def queryStats(
        self,
        patterns: Sequence[str] = ...,
        reset: bool = ...,
        regexp: bool = ...,
    ) -> dict[str, Any]: ...
    @property
    def running(self) -> bool: ...
    @property
    def handle(self) -> int: ...
    def __enter__(self) -> SingBox: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

def startFromJSON(json: str) -> None: ...

__version__: str
